### ISSUE TITLE
About your comment

### ISSUE THREAD

**Issue by jeromedecoster** [tj/d3-playground#2]
About your comment
https://github.com/tj/d3-playground/blob/master/webpack.config.js#L2

I'm surprised that you prefer using webpack/webpack-dev-server over simpler/lighter solution like browserify/express/koa.

It seems that you found it bloated/opaque, but still prefer it instead of your old projects and browserify.

Just curious.. why?

**Comment by tj** [comment]
Primarily for the react hot reloading stuff, though I've seen similar going on in browserify. I had issues with browserify being quite a bit slower but that was a while back
